export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ROBOTS_PENDING = 'REQUEST_ROBOTS_PENDING';
export const REQUEST_ROBOTS_RESOLVED = 'REQUEST_ROBOTS_RESOLVED';
export const REQUEST_ROBOTS_REJECTED = 'REQUEST_ROBOTS_REJECTED';